### ISSUE TITLE
a little slower

### ISSUE THREAD

**Issue by novat0** [dsoares/Roundcube-Plugin-Lastlogin#7] opened 2016-06-07 18:19 UTC
hello, i use your plugin, and its great, but i noted some slow performance in particular situations..

i only enabled your plugin and works perfect but disabling some seconds are gained!

thanks in advance!

**Comment by dsoares** [comment] 2016-06-09 18:56
Hi,
I think I know the reason for the slow performance and it should be explained in the README file.
I will try to look into it the next few days.

One question: what's your `geolocation_fetch_method` value ?
(see in `config.inc.php` from the `geolocation` plugin)

**Comment by dsoares** [comment] 2016-06-16 14:38
Any feedback here? What is your `geolocation_fetch_method` configuration value ?

This plugin does DNS name resolution and fetches geolocation information; that's why it adds some delay to the requests. I added a configuration option to turn ON/OFF the DNS feature and it will be included in the next release. 

To better understand the cause of slow performance, you may test in the lastlogin plugin configuration:
1. turn the DNS name resolution OFF (option `lastlogin_dns = false`) and check it's impact on performance;
2. turn geolocation plugin usage OFF (option `lastlogin_geolocation = false`) and check it's impact on performance;

**Closed** 2016-06-22 11:29 UTC
