### ISSUE TITLE
too slower when enable the lastlogin plugin

### ISSUE THREAD

**Issue by mckaygerhard** [dsoares/Roundcube-Plugin-Lastlogin#3] opened 2016-05-11 15:42 UTC
how can i depure due i not have any error unless the related of the array row[] assignee

when i enable the plugin and try to make the login process , just after input user&pasword and hit enter, boefore show the mails screen with preview takes around 12 to 15 seconds... 

without plugin log into in less of 2 seconds (counter of the chrome and my clock also)

with more clients, takes more! sometimes takes 30 seconds, in production i have 1200 users and 300 concurrently

**Comment by dsoares** [comment] 2016-05-11 17:03
Are you using the geolocation plugin? If yes, what fetch method have you configured? 
How fast is your DNS resolving ips?

**Comment by mckaygerhard** [comment] 2016-05-11 17:27
i triyed the followin:

1) activate only the blacklist plugin : works faster
2) activate both the blacklist and lastlogin+geoip: works slower
3) activate both the blacklist and lastlogin without geoip: works slower

do u said that DNS are the resolver of the ip, this are not simply taken from client and log in database when i loged in?

**Comment by mckaygerhard** [comment] 2016-05-11 17:51
i research more:

1) if the user are a new user, log in fast
2) if the user are a logn used account (have some preferences already in the users table) log in very slower!

and seems are more faster only with new users, older yet created users, does login very slower

**Comment by mckaygerhard** [comment] 2016-05-11 18:14
SOLVED: around line 88 in lastlogin.php file, the get_flag are innecesary, duie after renders the page the flag are dissapear!

this reduces the time in login for older users.. that's why new users dones not have slow login problems

in previous lines the flag are already checked, and if are valid state so renders page, so i double checked!

remove the getflag line in redenr hook and solves this issue!

**Comment by mckaygerhard** [comment] 2016-05-11 19:01
the pull request reduces the login but still persist some problems with server cache.. 

due i'm busy tomorrow i continue the test ... and then report more feedback

**Comment by dsoares** [comment] 2016-05-12 10:52
I'm going to accept your PR. I don't think this is the cause of the slowness you seem to report, but that extra check is indeed unnecessary.

**Closed by dsoares** 2016-05-12 10:52 UTC

**Comment by mckaygerhard** [comment] 2016-05-12 16:56
i cannot find the reason.. new users (first and second login without saved any configuration) log in quaickly.. 

but still long already current users (by example me, that i have enough saved data by example tags, filters and calendaring) log in very very slow (well not much but some seconds, around 10 to 18)

i'll continue investigate but i dont have enoug knowlegde, its a great work
